### ISSUE TITLE
Look at pricing for SSL certificate

### ISSUE THREAD

**Issue by melusi-k** [addcolouragency/ueda#5]

**Comment by khanyisa12** [comment]
I looked up at the pricings for SSL certificate 

1. Standard SSL which is R895.99/year. Its available in Domain Verification, Organisation Validation as well as Extended Validation SSL certificates
2. UCC/SAN SSL which is R1 959.99/year. its also available in DV,OV as well as EV SSL certificates.
3.Wildcard SSL which is R4 617.63/year. Its available in DV and OV SSL certificates.

**Comment by khanyisa12** [comment]
SSL CERTIFICATE PRICING
**1. COMODO**
Positive SSL (DV) | $7.02/yr.
Essential SSL (DV) | $21.95/yr.
Comodo EV SSL | $141.11/yr.
Instant SSL (OV) | $27.44/yr.
Instant SSL Premium (OV) | $54.09/yr.
Instant SSL Pro (OV) | $39.19/yr.
Comodo SSL Certificate (DV) | $48.61/yr.
Comodo Elite SSL (OV | $156.02/yr.
Enterprise SSL | $234.42/yr.
Enterprise SSL Pro | $555.86/yr.
Enterprise SSL Pro with EV | $861.62/yr.
Installation Service | $59.99/yr.

**2.GeoTrust**
GeoTrust True Business ID EV (FLEX) | $176.59/yr. | $1.5MM | Domain + Full   Business
GeoTrust True Business ID OV (FLEX) | $115.90/yr. | $1.25MM | Domain +   Basic Business
GeoTrust DV SSL (FLEX | $68.29/yr. | $500K | Domain
GeoTrust Quick SSL Premium SAN | $95.00/yr. | $500K | Domain
GeoTrust True Business ID with EV | $141.71/yr. | $1.5MM | Domain + Full Business
GeoTrust True Business ID w/ EV Multi-Domain | $299.25/yr. | $1.5MM | Domain + Full   Business

**3. Global Sign**
Domain Validated (DV)
$249 USD/ year
•	Issued in minutes; no paperwork required
•	Ideal for personal websites
•	Supports Wildcards and up to 100 SANs
Organization Validated (OV)
$349 USD/ year
•	Complete business authentication
•	Ideal for business websites
•	Supports Wildcards and up to 100 SANs
Extended Validated (EV)
$599 USD/ year
•	Company name displayed in browser
•	Ideal for ecommerce, financial institutions, common phishing targets
•	Supports up to 100 SANs

**4.NETWORK SOLUTIONS**
Xpress
Domain Validation
$59.99/year
with 2-year term
Basic
Full Organization Validation
$124.50/year
with 2-year term
Advanced
Fast Organization Validation
$199.50/year
with 2-year term
Wildcard
Unlimited Subdomains
$579.00/year
with 2-year term


These are the ones i have selected so far if you want i can change dollar to rand
